# Generated by Django 3.0.7 on 2020-07-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_auto_20200712_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='drink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drink.Drink'),
        ),
    ]
